In [1]:
import yfinance as yf
import pandas as pd

In [2]:
# List of cryptocurrencies
cryptos = [
    'BTC-USD', 'ETH-USD', 'BNB-USD', 'XRP-USD', 'ADA-USD',
    'SOL-USD', 'DOT-USD', 'DOGE-USD', 'LTC-USD', 'TRUMP35336-USD'
]

In [3]:
# Create an empty list to store dataframes for each cryptocurrency
dfs = []

# Loop through each cryptocurrency to fetch the data
for crypto in cryptos:
    # Fetch data for each cryptocurrency
    ticker = yf.Ticker(crypto)
    crypto_df = ticker.history(period="max")  # Fetch all available data

    # Rename columns to match the requested format
    crypto_df = crypto_df.reset_index().rename(columns={
        "Date": "Open Time",
        "Open": "Open",
        "High": "High",
        "Low": "Low",
        "Close": "Close",
        "Volume": "Volume"
    })

    # Add Close Time (Shift Open Time by 1 day to get Close Time)
    crypto_df["Close Time"] = crypto_df["Open Time"].shift(-1)

    # Add Number of Trades (Yahoo Finance doesn't provide direct trade count, so we use Volume as a proxy)
    crypto_df["Number of Trades"] = crypto_df["Volume"].astype(int)

    # Fetch Market Cap data from Yahoo Finance Key Statistics
    crypto_df["Market Cap"] = crypto_df["Close"] * crypto_df["Volume"]  # Approximation as Yahoo doesn't provide direct market cap

    # Add the symbol as a new column
    crypto_df["Symbol"] = crypto

    # Select required columns
    crypto_df = crypto_df[["Open Time", "Open", "High", "Low", "Close", "Volume", "Close Time", "Number of Trades", "Market Cap", "Symbol"]]

    # Add the dataframe to the list
    dfs.append(crypto_df)

# Concatenate all the dataframes into a single dataframe
final_df = pd.concat(dfs, ignore_index=True)

# Format Market Cap as a string with commas
final_df["Market Cap (USD)"] = final_df["Market Cap"].apply(lambda x: "{:,.2f}".format(x))

In [4]:
final_df

,Open Time,Open,High,Low,Close,Volume,Close Time,Number of Trades,Market Cap,Symbol,Market Cap (USD)
0,2014-09-17 00:00:00+00:00,465.864014,468.174011,452.421997,457.334015,21056800,2014-09-18 00:00:00+00:00,21056800,9.629991e+09,BTC-USD,"9,629,990,884.79"
1,2014-09-18 00:00:00+00:00,456.859985,456.859985,413.104004,424.440002,34483200,2014-09-19 00:00:00+00:00,34483200,1.463605e+10,BTC-USD,"14,636,049,492.19"
2,2014-09-19 00:00:00+00:00,424.102997,427.834991,384.532013,394.795990,37919700,2014-09-20 00:00:00+00:00,37919700,1.497055e+10,BTC-USD,"14,970,545,501.63"
3,2014-09-20 00:00:00+00:00,394.673004,423.295990,389.882996,408.903992,36863600,2014-09-21 00:00:00+00:00,36863600,1.507367e+10,BTC-USD,"15,073,673,188.40"
4,2014-09-21 00:00:00+00:00,408.084991,412.425995,393.181000,398.821014,26580100,2014-09-22 00:00:00+00:00,26580100,1.060070e+10,BTC-USD,"10,600,702,444.97"
...,...,...,...,...,...,...,...,...,...,...,...
24308,2025-02-09 00:00:00+00:00,17.272690,17.857498,15.371288,15.910079,1239266372,2025-02-10 00:00:00+00:00,1239266372,1.971683e+10,TRUMP35336-USD,"19,716,825,883.51"
24309,2025-02-10 00:00:00+00:00,15.910079,16.474728,14.791062,15.894214,1367573432,2025-02-11 00:00:00+00:00,1367573432,2.173650e+10,TRUMP35336-USD,"21,736,504,346.45"
24310,2025-02-11 00:00:00+00:00,15.894214,16.744793,15.254589,15.339934,905289209,2025-02-12 00:00:00+00:00,905289209,1.388708e+10,TRUMP35336-USD,"13,887,077,032.97"
24311,2025-02-12 00:00:00+00:00,15.339941,15.531578,14.647069,15.440720,871319046,2025-02-14 00:00:00+00:00,871319046,1.345379e+10,TRUMP35336-USD,"13,453,793,075.34"
24312,2025-02-14 00:00:00+00:00,16.279863,16.433805,15.879763,16.431963,2258442496,NaT,-2036524800,3.711064e+10,TRUMP35336-USD,"37,110,643,457.19"

In [17]:
pd.reset_option('display.max_rows')

In [6]:
final_df.drop(columns=[
    'Number of Trades',
    'Market Cap',
    'Market Cap (USD)'
],inplace=True)
final_df

,Open Time,Open,High,Low,Close,Volume,Close Time,Symbol
0,2014-09-17 00:00:00+00:00,465.864014,468.174011,452.421997,457.334015,21056800,2014-09-18 00:00:00+00:00,BTC-USD
1,2014-09-18 00:00:00+00:00,456.859985,456.859985,413.104004,424.440002,34483200,2014-09-19 00:00:00+00:00,BTC-USD
2,2014-09-19 00:00:00+00:00,424.102997,427.834991,384.532013,394.795990,37919700,2014-09-20 00:00:00+00:00,BTC-USD
3,2014-09-20 00:00:00+00:00,394.673004,423.295990,389.882996,408.903992,36863600,2014-09-21 00:00:00+00:00,BTC-USD
4,2014-09-21 00:00:00+00:00,408.084991,412.425995,393.181000,398.821014,26580100,2014-09-22 00:00:00+00:00,BTC-USD
...,...,...,...,...,...,...,...,...
24308,2025-02-09 00:00:00+00:00,17.272690,17.857498,15.371288,15.910079,1239266372,2025-02-10 00:00:00+00:00,TRUMP35336-USD
24309,2025-02-10 00:00:00+00:00,15.910079,16.474728,14.791062,15.894214,1367573432,2025-02-11 00:00:00+00:00,TRUMP35336-USD
24310,2025-02-11 00:00:00+00:00,15.894214,16.744793,15.254589,15.339934,905289209,2025-02-12 00:00:00+00:00,TRUMP35336-USD
24311,2025-02-12 00:00:00+00:00,15.339941,15.531578,14.647069,15.440720,871319046,2025-02-14 00:00:00+00:00,TRUMP35336-USD
24312,2025-02-14 00:00:00+00:00,16.279863,16.433805,15.879763,16.431963,2258442496,NaT,TRUMP35336-USD

In [8]:
import yfinance as yf

# Define the cryptocurrency ticker (Bitcoin in this case)
for crypto in cryptos:

# Fetch data for Bitcoin
    btc = yf.Ticker(crypto)

# Get market cap data
    market_cap = btc.info['marketCap']

# Print the market cap
    print(f"Market Cap of {crypto}: ${market_cap:,.2f}")

Market Cap of BTC-USD: $1,918,643,470,336.00
Market Cap of ETH-USD: $325,273,780,224.00
Market Cap of BNB-USD: $96,975,503,360.00
Market Cap of XRP-USD: $148,621,557,760.00
Market Cap of ADA-USD: $28,373,860,352.00
Market Cap of SOL-USD: $95,397,732,352.00
Market Cap of DOT-USD: $8,039,134,720.00
Market Cap of DOGE-USD: $38,826,995,712.00
Market Cap of LTC-USD: $9,571,279,872.00
Market Cap of TRUMP35336-USD: $3,280,496,640.00

In [9]:
final_df.to_csv('C:/Users/ssoba/OneDrive/Desktop/Binance Analysis/data.csv', index=False)
print("Saved")

Saved

In [10]:
import pandas as pd



cryptos = [
    "BTC-USD", "ETH-USD", "BNB-USD", "XRP-USD", "ADA-USD",
    "SOL-USD", "DOT-USD", "DOGE-USD", "LTC-USD", "TRUMP35336-USD"
]

symbol_to_name = {
    "BTC-USD": "Bitcoin",
    "ETH-USD": "Ethereum",
    "BNB-USD": "Binance Coin",
    "XRP-USD": "XRP",
    "ADA-USD": "Cardano",
    "SOL-USD": "Solana",
    "DOT-USD": "Polkadot",
    "DOGE-USD": "Dogecoin",
    "LTC-USD": "Litecoin",
    "TRUMP35336-USD": "Trump Coin"
}


coin_df =  pd.DataFrame({"Symbol": cryptos, "Coin Name": [symbol_to_name.get(sym, "Unknown") for sym in cryptos]})  
coin_df

           Symbol     Coin Name
0         BTC-USD       Bitcoin
1         ETH-USD      Ethereum
2         BNB-USD  Binance Coin
3         XRP-USD           XRP
4         ADA-USD       Cardano
5         SOL-USD        Solana
6         DOT-USD      Polkadot
7        DOGE-USD      Dogecoin
8         LTC-USD      Litecoin
9  TRUMP35336-USD    Trump Coin

In [11]:
import yfinance as yf

market = {}
# Define the cryptocurrency ticker (Bitcoin in this case)
for crypto in cryptos:

# Fetch data for Bitcoin
    btc = yf.Ticker(crypto)

# Get market cap data
    market_cap = btc.info['marketCap']

# Print the market cap
    market[crypto] = market_cap
market

{'BTC-USD': 1931028856832,
 'ETH-USD': 325658902528,
 'BNB-USD': 93692878848,
 'XRP-USD': 160964345856,
 'ADA-USD': 28121288704,
 'SOL-USD': 95828008960,
 'DOT-USD': 7895826432,
 'DOGE-USD': 40922083328,
 'LTC-USD': 9838770176,
 'TRUMP35336-USD': 4212107520}

In [12]:
coin_df['Market Cap'] = coin_df['Symbol'].map(market)
coin_df

           Symbol     Coin Name     Market Cap
0         BTC-USD       Bitcoin  1931028856832
1         ETH-USD      Ethereum   325658902528
2         BNB-USD  Binance Coin    93692878848
3         XRP-USD           XRP   160964345856
4         ADA-USD       Cardano    28121288704
5         SOL-USD        Solana    95828008960
6         DOT-USD      Polkadot     7895826432
7        DOGE-USD      Dogecoin    40922083328
8         LTC-USD      Litecoin     9838770176
9  TRUMP35336-USD    Trump Coin     4212107520

In [13]:
coin_df.to_csv('C:/Users/ssoba/OneDrive/Desktop/Binance Analysis/coin_data.csv', index=False)
print("Saved")

Saved